"""HTML report generator — Plotly.js horizontal bar charts."""
from __future__ import annotations

import json
from pathlib import Path

import openpyxl

RANK_COLORS = ["#2e7d32", "#f9a825", "#d84315", "#546e7a"]

TEMPLATE = """<!DOCTYPE html>
<html lang="zh">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  * {{ margin:0; padding:0; box-sizing:border-box; }}
  body {{ font-family:'Microsoft YaHei',sans-serif; background:#f0f2f5; padding:20px; }}
  .container {{ max-width:1200px; margin:0 auto; }}
  h1 {{ font-size:22px; color:#1a1a2e; margin-bottom:4px; }}
  .subtitle {{ color:#888; font-size:13px; margin-bottom:20px; }}
  .chart-row {{ display:flex; gap:16px; margin-bottom:16px; flex-wrap:wrap; }}
  .chart-card {{ flex:1; min-width:420px; background:#fff; border-radius:10px;
    box-shadow:0 2px 12px rgba(0,0,0,.06); padding:16px; }}
  .chart-card h3 {{ font-size:15px; color:#333; margin-bottom:8px; }}
  table {{ width:100%; border-collapse:collapse; background:#fff; border-radius:10px;
    box-shadow:0 2px 12px rgba(0,0,0,.06); margin-top:16px; }}
  th {{ background:#2b579a; color:#fff; padding:10px 12px; text-align:center; font-size:13px; }}
  td {{ padding:8px 12px; text-align:center; border-bottom:1px solid #eee; font-size:13px; }}
  tr:hover td {{ background:#f0f4ff; }}
  .note {{ color:#999; font-size:12px; margin-top:16px; }}
</style>
</head>
<body>
<div class="container">
<h1>{title}</h1>
<div class="subtitle">{subtitle}</div>
<div class="chart-row">
  {charts}
</div>
{ranking_table}
<div class="note">Generated by RAG-Pro</div>
</div>
<script>
  {plot_script}
</script>
</body>
</html>"""


def generate_report(scored_xlsx: str, output_html: str, title: str = "RAG 评测报告"):
    """从 scored.xlsx 生成 HTML 报告，展示最优轮平均分 + 全量平均分 + 召回率。"""
    wb = openpyxl.load_workbook(scored_xlsx)

    if "综合评分" not in wb.sheetnames:
        print("警告: 缺少综合评分 sheet，跳过报告生成")
        return

    ws = wb["综合评分"]
    strategies = []
    best_avgs = []
    all_avgs = []
    for row in range(2, ws.max_row + 1):
        name = ws.cell(row=row, column=1).value
        best = ws.cell(row=row, column=2).value
        all_ = ws.cell(row=row, column=3).value
        if name and best is not None:
            strategies.append(str(name))
            best_avgs.append(round(float(best), 2))
            all_avgs.append(round(float(all_), 2) if all_ is not None else round(float(best), 2))

    if not strategies:
        print("警告: 无评分数据")
        return

    # 召回率
    recall_rates = {}
    if "汇总" in wb.sheetnames:
        ws_hz = wb["汇总"]
        hdrs = [str(ws_hz.cell(row=1, column=c).value or "") for c in range(1, ws_hz.max_column + 1)]
        recall_col_map = {}
        for ci, h in enumerate(hdrs):
            if h.endswith("_召回"):
                sname = h.replace("_召回", "")
                recall_col_map[sname] = ci + 1
        for sname, col in recall_col_map.items():
            hits = 0
            total = 0
            for r in range(2, ws_hz.max_row + 1):
                v = ws_hz.cell(row=r, column=col).value
                if v is not None:
                    hits += int(v)
                    total += 1
            if total > 0:
                recall_rates[sname] = round(hits / total * 100, 1)

    # 按最优轮平均分降序排列
    combined = sorted(zip(strategies, best_avgs, all_avgs), key=lambda x: x[1], reverse=True)
    strategies, best_avgs, all_avgs = zip(*combined) if combined else ([], [], [])

    has_runs = any(a != b for a, b in zip(best_avgs, all_avgs))

    # 排名表格
    rows = ""
    for i, (sname, best, all_) in enumerate(zip(strategies, best_avgs, all_avgs)):
        recall = recall_rates.get(sname)
        recall_str = f"{recall}%" if recall is not None else "--"
        rows += f"<tr><td>{i+1}</td><td>{sname}</td><td>{best}</td><td>{all_}</td><td>{recall_str}</td></tr>\n"
    ranking_table = f"""<table>
<tr><th>排名</th><th>策略</th><th>最优轮平均分</th><th>全量平均分</th><th>召回率</th></tr>
{rows}</table>"""

    # 柱状图数据（从下往上渲染，反转数组）
    plot_names = list(reversed(list(strategies)))
    plot_best = list(reversed(list(best_avgs)))
    plot_all = list(reversed(list(all_avgs)))
    plot_recalls = list(reversed([recall_rates.get(s, 0) for s in strategies]))

    # 得分图：双柱 (最优轮 vs 全量)
    if has_runs:
        score_traces = f"""
  {{ type: 'bar', x: plot_best, y: plot_names, orientation: 'h', name: '最优轮',
    marker: {{ color: '#2e7d32' }}, text: plot_best.map(v => v.toFixed(1)), textposition: 'outside' }},
  {{ type: 'bar', x: plot_all, y: plot_names, orientation: 'h', name: '全量',
    marker: {{ color: '#90a4ae' }}, text: plot_all.map(v => v.toFixed(1)), textposition: 'outside' }}"""
    else:
        score_traces = """
  { type: 'bar', x: plot_best, y: plot_names, orientation: 'h', name: '平均总分',
    marker: { color: plot_best.map((_, i) => colors[plot_names.length - 1 - i] || '#546e7a') },
    text: plot_best.map(v => v.toFixed(1)), textposition: 'outside' }"""

    plot_script = f"""
const plot_names = {json.dumps(plot_names, ensure_ascii=False)};
const plot_best = {json.dumps(plot_best)};
const plot_all = {json.dumps(plot_all)};
const plot_recalls = {json.dumps(plot_recalls)};
const colors = {json.dumps(RANK_COLORS)};

Plotly.newPlot('chart-score', [{score_traces}
], {{
  margin: {{ l: 180, r: 60, t: 10, b: 30 }},
  xaxis: {{ title: '得分', range: [0, Math.max(...plot_best, ...plot_all) * 1.15] }},
  yaxis: {{ automargin: true }},
  barmode: 'group',
}}, {{ responsive: true }});

Plotly.newPlot('chart-recall', [{{
  type: 'bar',
  x: plot_recalls,
  y: plot_names,
  orientation: 'h',
  marker: {{ color: plot_recalls.map((_, i) => colors[plot_names.length - 1 - i] || '#546e7a') }},
  text: plot_recalls.map(v => v.toFixed(1) + '%'),
  textposition: 'outside',
}}], {{
  margin: {{ l: 180, r: 60, t: 10, b: 30 }},
  xaxis: {{ title: '召回率 (%)', range: [0, Math.max(...plot_recalls, 10) * 1.2] }},
  yaxis: {{ automargin: true }},
}}, {{ responsive: true }});
"""

    score_title = "最优轮 vs 全量平均分" if has_runs else "平均总分"
    charts = f"""
  <div class="chart-card">
    <h3>{score_title}（降序）</h3>
    <div id="chart-score" class="plot" style="height:400px;"></div>
  </div>
  <div class="chart-card">
    <h3>召回率</h3>
    <div id="chart-recall" class="plot" style="height:400px;"></div>
  </div>"""

    subtitle = f"共 {len(strategies)} 个策略，数据来源: {Path(scored_xlsx).name}"
    html = TEMPLATE.format(
        title=title, subtitle=subtitle,
        charts=charts, ranking_table=ranking_table, plot_script=plot_script,
    )

    Path(output_html).write_text(html, encoding="utf-8")
    print(f"报告已生成: {output_html}")


def generate_recall_report(input_xlsx: str, output_html: str, title: str = "RAG 召回率评测"):
    """从 recall.xlsx 生成纯召回率报告。"""
    wb = openpyxl.load_workbook(input_xlsx)

    if "综合召回" not in wb.sheetnames:
        print("警告: 缺少综合召回 sheet，跳过报告生成")
        return

    ws = wb["综合召回"]
    strategies = []
    rates = []
    merged_rates = []
    concat_rates = []
    file_rates = []
    positions = []
    for row in range(2, ws.max_row + 1):
        name = ws.cell(row=row, column=1).value
        rate = ws.cell(row=row, column=2).value
        merged_r = ws.cell(row=row, column=3).value
        concat_r = ws.cell(row=row, column=4).value
        pos = ws.cell(row=row, column=5).value
        file_r = ws.cell(row=row, column=6).value
        if name and rate is not None:
            strategies.append(str(name))
            rates.append(round(float(rate), 1))
            merged_rates.append(round(float(merged_r), 1) if merged_r is not None else 0)
            concat_rates.append(round(float(concat_r), 1) if concat_r is not None else 0)
            file_rates.append(round(float(file_r), 1) if file_r is not None else 0)
            positions.append(str(pos))

    if not strategies:
        print("警告: 无数据")
        return

    # 按召回率降序
    combined = sorted(zip(strategies, rates, merged_rates, concat_rates, file_rates, positions),
                      key=lambda x: x[1], reverse=True)
    strategies, rates, merged_rates, concat_rates, file_rates, positions = zip(*combined) if combined else ([], [], [], [], [], [])

    # 排名表
    rows = ""
    for i, (sname, rate, mrate, crate, frate, pos) in enumerate(
            zip(strategies, rates, merged_rates, concat_rates, file_rates, positions)):
        rows += f"<tr><td>{i+1}</td><td>{sname}</td><td>{rate}%</td><td>{mrate}%</td><td>{crate}%</td><td>{frate}%</td><td>{pos}</td></tr>\n"
    ranking_table = f"""<table>
<tr><th>排名</th><th>策略</th><th>召回率</th><th>合并召回率</th><th>拼接召回率</th><th>文件召回率</th><th>平均命中位置</th></tr>
{rows}</table>"""

    # 柱状图：双柱 (内容 vs 文件)
    plot_names = list(reversed(list(strategies)))
    plot_rates = list(reversed(list(rates)))
    plot_files = list(reversed(list(file_rates)))
    plot_script = f"""
const names = {json.dumps(plot_names, ensure_ascii=False)};
const rates = {json.dumps(plot_rates)};
const files = {json.dumps(plot_files)};
const colors = {json.dumps(RANK_COLORS)};

Plotly.newPlot('chart-recall', [{{
  type: 'bar', x: rates, y: names, orientation: 'h', name: '内容召回',
  marker: {{ color: '#2e7d32' }}, text: rates.map(v => v.toFixed(1) + '%'), textposition: 'outside'
}}, {{
  type: 'bar', x: files, y: names, orientation: 'h', name: '文件召回',
  marker: {{ color: '#f9a825' }}, text: files.map(v => v.toFixed(1) + '%'), textposition: 'outside'
}}], {{
  margin: {{ l: 180, r: 60, t: 10, b: 30 }},
  xaxis: {{ title: '召回率 (%)', range: [0, Math.max(...rates, ...files) * 1.2] }},
  yaxis: {{ automargin: true }},
  barmode: 'group',
}}, {{ responsive: true }});
"""

    charts = """
  <div class="chart-card">
    <h3>召回率 — 内容 vs 文件（降序）</h3>
    <div id="chart-recall" class="plot" style="height:400px;"></div>
  </div>"""

    subtitle = f"共 {len(strategies)} 个策略，数据来源: {Path(input_xlsx).name}  |  纯召回率评测，无 LLM 调用"
    html = TEMPLATE.format(
        title=title, subtitle=subtitle,
        charts=charts, ranking_table=ranking_table, plot_script=plot_script,
    )

    Path(output_html).write_text(html, encoding="utf-8")
    print(f"报告已生成: {output_html}")
